server:
  port: 8080
  servlet:
    context-path: "/bookstore-api"
spring:
  application:
    name: BookStore
  flyway:
    enabled: true
    locations: "classpath:db/migration"
    baseline-on-migrate: true
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/bookstore
    username: my_user
    password: my_secret
  liquibase:
    enabled: false
  logging:
    level:
      org.springframework.r2dbc: DEBUG # Nível de log para R2DBC (opcional)

springdoc:
  api-docs:
    enabled: false
    path: "/v3/api-docs"
  swagger-ui:
    url: "/api-docs.yaml"

jwt:
  secret: "chave-de-seguranca"
  enabled: true
