server:
  port: 8080
  servlet:
    context-path: "/bookstore-api"
spring:
  application:
    name: BookStore
  flyway:
    enabled: true
    locations: "classpath:db/migration"
    baseline-on-migrate: true
  datasource:
    url: jdbc:postgresql://localhost:5432/bookstore
    username: my_user
    password: my_secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  api-docs:
    enabled: false
    path: "/v3/api-docs"
  swagger-ui:
    url: "/api-docs.yaml"

jwt:
  secret: "chave-de-seguranca"
  enabled: true

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, info
      discovery:
        enabled: true
  endpoint:
    health:
      show-details: always
      show-components: always

info:
  app:
    name: Bookstore API
    description: API para gerenciamento de livros.
    version: 1.0.0
    database: PostgreSQL
    authentication: Bearer JWT

