spring:
  application:
    name: BookStore
  flyway:
    enabled: true
    locations: "classpath:db/migration"
    baseline-on-migrate: true
  datasource:
    url: jdbc:postgresql://localhost:5432/bookstore
    username: my_user
    password: my_secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  api-docs:
    enabled: false
    path: "/v3/api-docs"
  swagger-ui:
    url: "/api-docs.yaml"
