INSERT INTO bookstore.author (NAME)
VALUES ('Machado de Assis'),
       ('Fernando Pessoa'),
       ('Jorge Amado'),
       ('Clarice Lispector'),
       ('Érico Veríssimo'),
       ('Graciliano Ramos'),
       ('Guimarães Rosa'),
       ('Cecília Meireles'),
       ('Carlos Drummond de Andrade'),
       ('José Saramago'),
       ('Rubem Fonseca'),
       ('Ariano Suassuna'),
       ('João Cabral de Melo Neto'),
       ('Manoel de Barros'),
       ('Monteiro Lobato'),
       ('Paulo Coelho'),
       ('Raduan Nassar'),
       ('Lygia Fagundes Telles'),
       ('Adélia Prado'),
       ('Ana Maria Machado');
